version: "3.9"

services:
  backend:
    build:
      context: ./backend
    command: gunicorn backend.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - vue_build:/frontend/dist/
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - vue_build:/var/www/vue
    depends_on:
      - backend
      - frontend
volumes:
  vue_build:
